### ISSUE TITLE
Error if 'context' inside the task title when adding using tw

### ISSUE THREAD

**Issue by mikelnrd** [coddingtonbear/taskwarrior-context-capsule#1]
Hi.  Great to be able to start using contexts so thanks!

Found what I think is a small bug...

I did the following:
tw context define work +w
tw context work
tw add testing work context

The third line seems to fail because of the word 'context' inside the task title.  It gives the following error: "The context taskwarrior capsule encountered an error processing your request: No context command specified"
however the command... "tw add testing work contexts" works fine.

**Comment by mokrunka** [comment]
Closing this issue as this repo has been superceded by the main taskwarrior project.

See https://taskwarrior.org/docs/context.html
