### ISSUE TITLE
Consider marking this repository as superseded by taskwarrior

### ISSUE THREAD

**Issue by MartyLake** [coddingtonbear/taskwarrior-context-capsule#2]
Hi,

Can you consider archive this repository and mark it as superseded by taskwarrior now that is supports context already https://taskwarrior.org/docs/context.html ?

Best,

**Comment by mokrunka** [comment]
Hi @MartyLake, I am the new owner of the taskwarrior-context-capsule repo, after the original owner tranferred it to me. I'm currently running through issues and found yours. I'm happy to do your suggestion - could you please show me how to do that?

**Comment by MartyLake** [comment]
Sure, see https://github.com/mokrunka/taskwarrior-context-capsule/pull/3

**Comment by mokrunka** [comment]
Thanks @MartyLake
